name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:    
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-electron:
    name: Make Electron
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os:
          - name: linux
            image: ubuntu-latest
            extension: deb
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Update build info
        run: npm run update-build-info      
      - name: Run electron-forge
        run: npm run make-electron -- --arch=${{ matrix.arch }}
      - name: Prepare artifacts (Unix)
        run: |
          mkdir -p upload
          file=$(find out/make -name '*.${{ matrix.os.extension }}' -print -quit)
          cp "$file" "upload/TriliumRain-${{ matrix.os.name }}-${{ matrix.arch }}-${{ github.ref_name }}.${{ matrix.os.extension }}"
      - name: Publish installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TriliumRain ${{ matrix.os.name }} ${{ matrix.arch }}.${{matrix.os.extension}}
          path: upload/*.${{ matrix.os.extension }}
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          files: upload/*.*
